#!/bin/bash
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J filter_SRA_sc_004
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=2000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --output=/global/projectb/scratch/byu24/at.sc.db/log/filter_SRA_sc_004.out

module load python3
source activate $BSCRATCH/bin/env_STARsolo
cd $BSCRATCH/at.sc.db/

sh /global/projectb/scratch/byu24/at.sc.db/src/trim_filter.sh sc_004 DropSeq
