#!/bin/bash
#SBATCH -N 1
#SBATCH -c 32
#SBATCH -C skylake
#SBATCH --mem-per-cpu=2000
#SBATCH -t 4:00:00
#SBATCH -A gtrnd
#SBATCH -q jgi_exvivo
#SBATCH -J analyze
#SBATCH --output=$BSCRATCH/at.sc.db/log/analyze.out


module load python3
source activate /global/projectb/scratch/bjcole/env/scRNAseq2
cd $BSCRATCH/at.sc.db/
mkdir scratch/analysis
echo "################################################################################" >> log/analyze.Rout
date >> log/analyze.Rout
echo "################################################################################" >> log/analyze.Rout
R CMD BATCH $BSCRATCH/at.sc.db/src/analyze/plan.R >> $BSCRATCH/at.sc.db/log/analyze.Rout
