#!/bin/bash
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J dc_021_run
#SBATCH -t 24:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --output=dc_021_run.out

module load python3
source activate /global/projectb/scratch/bjcole/env_STARsolo
cd /global/projectb/scratch/bjcole/at.sc.db/
mkdir scratch/dc_021

cat data/whitelist.txt > \
  scratch/dc_021/dc_021_whitelist.csv
STAR \
  --genomeDir scratch/genomes/at10 \
  --readFilesIn scratch/dc_021/dc_021_R2.fastq scratch/dc_021/dc_021_R1.fastq \
  --soloCBwhitelist scratch/dc_021/dc_021_whitelist.csv \
  --outFileNamePrefix scratch/dc_021/dc_021_star. \
  --soloType Droplet \
  --soloCBlen 16 \
  --soloUMIlen 10 \
  --soloUMIstart 17 \
  --runThreadN 8
