#!/bin/bash
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J js_018_run
#SBATCH -t 24:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --output=js_018_run.out

module load python3
source activate /global/projectb/scratch/bjcole/env_STARsolo
cd /global/projectb/scratch/bjcole/at.sc.db/
mkdir scratch/js_018

cat data/whitelist.txt > \
  scratch/js_018/js_018_whitelist.csv
STAR \
  --genomeDir scratch/genomes/at10 \
  --readFilesIn scratch/js_018/js_018_R2.fastq scratch/js_018/js_018_R1.fastq \
  --soloCBwhitelist scratch/js_018/js_018_whitelist.csv \
  --outFileNamePrefix scratch/js_018/js_018_star. \
  --soloType Droplet \
  --soloCBlen 16 \
  --soloUMIlen 10 \
  --soloUMIstart 17 \
  --runThreadN 8
