
sbatch src/map/ss_001_run.bs &
sbatch src/map/ss_002_run.bs &
sbatch src/map/ss_003_run.bs &
sbatch src/map/sc_004_run.bs &
sbatch src/map/sc_005_run.bs &
sbatch src/map/sc_006_run.bs &
sbatch src/map/sc_007_run.bs &
sbatch src/map/sc_008_run.bs &
sbatch src/map/sc_009_run.bs &
sbatch src/map/sc_010_run.bs &
sbatch src/map/zc_011_run.bs &
sbatch src/map/rc_012_run.bs &
sbatch src/map/rc_013_run.bs &
sbatch src/map/rc_014_run.bs &
sbatch src/map/rc_015_run.bs &
sbatch src/map/jsh_016_run.bs &
sbatch src/map/js_017_run.bs &
sbatch src/map/js_018_run.bs &
sbatch src/map/dc_019_run.bs &
sbatch src/map/dc_020_run.bs &
sbatch src/map/dc_021_run.bs &
sbatch src/map/dc_022_run.bs &
