#!/bin/bash
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J ss_002_run
#SBATCH -t 24:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --output=ss_002_run.out

module load python3
source activate /global/projectb/scratch/bjcole/env_STARsolo
cd /global/projectb/scratch/bjcole/at.sc.db/
mkdir scratch/ss_002


sh src/map/map_dropseq.sh \
  --in1=scratch/ss_002/ss_002_R1.fastq \
  --in2=scratch/ss_002/ss_002_R2.fastq \
  --run_type=DropSeq \
  --run_name=ss_002 \
  --genome=at10_hg38 \
  --parent_dir=scratch/

awk '{if(NR > 1) {print $1}}' scratch/ss_002/ss_002_synthesis_error_stats.txt > \
  scratch/ss_002/ss_002_whitelist.csv

STAR \
  --genomeDir scratch/genomes/at10_hg38 \
  --readFilesIn scratch/ss_002/ss_002_R2.fastq scratch/ss_002/ss_002_R1.fastq \
  --soloCBwhitelist scratch/ss_002/ss_002_whitelist.csv \
  --outFileNamePrefix scratch/ss_002/ss_002_star. \
  --soloType Droplet \
  --soloCBlen 12 \
  --soloUMIlen 8 \
  --soloUMIstart 13 \
  --runThreadN 8
