#!/bin/bash
#SBATCH --mail-user=brendayu@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J download_SRA_zc_011
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --output=download_SRA_zc_011.out

module load python3
conda create --mkdir --prefix=/global/projectb/scratch/byu24/bin/env_STAR
source activate /global/projectb/scratch/byu24/bin/env_STAR
cd /global/projectb/scratch/byu24/at.sc.db/
wget ftp://download.big.ac.cn/gsa/CRA001559/CRR054647/CRR054647_f1.tar.gz -O scratch/zc_011_1.tar.gz
tar -xzvf scratch/zc_011_1.tar.gz -C scratch/
zcat scratch/Root_R1.fastq.gz > scratch/zc_011_1.fastq
wget ftp://download.big.ac.cn/gsa/CRA001559/CRR054647/CRR054647_r2.fastq.gz -O scratch/zc_011_2.fastq.gz
zcat scratch/zc_011_2.fastq.gz > scratch/zc_011_2.fastq
