#!/bin/bash
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J download_SRA_zc_011
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --output=download_SRA_zc_011.out

module load python3
source activate /global/projectb/scratch/bjcole/env_STARsolo
cd /global/projectb/scratch/bjcole/at.sc.db/

mkdir scratch/zc_011
wget ftp://download.big.ac.cn/gsa/CRA001559/CRR054647/CRR054647_f1.tar.gz -O scratch/zc_011/zc_011_1.tar.gz
tar -xzvf scratch/zc_011/zc_011_1.tar.gz -C scratch/zc_011/
zcat scratch/zc_011/Root_R1.fastq.gz > scratch/zc_011/zc_011_1.fastq
wget ftp://download.big.ac.cn/gsa/CRA001559/CRR054647/CRR054647_r2.fastq.gz -O scratch/zc_011/zc_011_2.fastq.gz
zcat scratch/zc_011/zc_011_2.fastq.gz > scratch/zc_011/zc_011_2.fastq
