#!/bin/bash
#SBATCH --mail-user=brendayu@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J download_SRA_rc_012
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --output=download_SRA_rc_012.out

module load python3
conda create --mkdir --prefix=$BSCRATCH/env_STAR
source activate $BSCRATCH/env_STAR
cd /global/projectb/scratch/byu24/at.sc.db/
/global/projectb/scratch/byu24/bin/sratoolkit.2.9.6-1-ubuntu64/bin/prefetch.2.9.3 SRR8257103 -o scratch/rc_012 -t http
/global/projectb/scratch/byu24/bin/sratoolkit.2.9.6-1-ubuntu64/bin/fasterq-dump scratch/rc_012 \
  -o rc_012.fastq \
  -O /global/projectb/scratch/byu24/at.sc.db/scratch \
  -t /global/projectb/scratch/byu24/at.sc.db/scratch \
  -sS --include-technical
