#!/bin/bash
#SBATCH --mail-user=bjcole@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J download_SRA_jsh_016
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --output=download_SRA_jsh_016.out

module load python3
source activate /global/projectb/scratch/bjcole/env_STARsolo
cd /global/projectb/scratch/bjcole/at.sc.db/
wget ftp://ftp.sra.ebi.ac.uk/vol1/run/SRR808/SRR8086586/whole_root_Heatshock_possorted_genome_bam.bam \
  -q -O- | samtools view | \
    awk '{ \
    match($0, "CR:Z:([ATCGN]+)", arr1)
    match($0, "UR:Z:([ATCGN]+)", arr2)
    match($0, "CY:Z:([[:graph:]]+)", arr3)
    match($0, "UY:Z:([[:graph:]]+)", arr4)
    print $1"\n" arr1[1] arr2[1] "\n+\n" arr3[1] arr4[1] > "scratch/jsh_016_1.fastq"
    print $1"\n"$10"\n+\n"$11 > "scratch/jsh_016_2.fastq"}'
