sbatch src/download/download_ss_001.bs &
sbatch src/download/download_ss_002.bs &
sbatch src/download/download_ss_003.bs &
sbatch src/download/download_sc_004.bs &
sbatch src/download/download_sc_005.bs &
sbatch src/download/download_sc_006.bs &
sbatch src/download/download_sc_007.bs &
sbatch src/download/download_sc_008.bs &
sbatch src/download/download_sc_009.bs &
sbatch src/download/download_sc_010.bs &
sbatch src/download/download_zc_011.bs &
sbatch src/download/download_rc_012.bs &
sbatch src/download/download_rc_013.bs &
sbatch src/download/download_rc_014.bs &
sbatch src/download/download_rc_015.bs &
sbatch src/download/download_jsh_016.bs &
sbatch src/download/download_js_017.bs &
sbatch src/download/download_js_018.bs &
sbatch src/download/download_dc_019.bs &
sbatch src/download/download_dc_020.bs &
sbatch src/download/download_dc_021.bs &
sbatch src/download/download_dc_022.bs &
