#!/bin/bash
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J shuffle_jsh_016
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --output=$BSCRATCH/at.sc.db/log/shuffle_jsh_016.out

cd $BSCRATCH/at.sc.db/scratch

sh $BSCRATCH/bin/bbmap/shuffle2.sh in1=jsh_016_R1.fastq in2=jsh_016_R2.fastq out1=jsh_016_tmp1.fastq out2=jsh_016_tmp2.fastq

head -n 4000000 jsh_016_tmp1.fastq > jsh_016_tmpR1.fastq
head -n 4000000 jsh_016_tmp2.fastq > jsh_016_tmpR2.fastq