#!/bin/bash
#SBATCH --mail-user=brendayu@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J alevin_SRA_sc_005
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --output=/global/projectb/scratch/byu24/at.sc.db/log/alevin_SRA_sc_005.out

cd /global/projectb/scratch/byu24/at.sc.db/

sh src/salmon_pipeline.sh sc_005 DropSeq
