#!/bin/bash
#SBATCH --mail-user=bjcole@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -A gtrnd
#SBATCH -q genepool_shared
#SBATCH -J download_SRA_set_022
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --output=download_SRA_set_022.out

/global/projectb/scratch/bjcole/sratoolkit.2.9.6-1-ubuntu64/bin/prefetch.2.9.3 SRR8315908 -o /global/projectb/scratch/bjcole/at.sc.db/scratch/set_022 -t http
/global/projectb/scratch/bjcole/sratoolkit.2.9.6-1-ubuntu64/bin/fasterq-dump /global/projectb/scratch/bjcole/at.sc.db/scratch/set_022 \
  -o set_022.fastq \
  -O /global/projectb/scratch/bjcole/at.sc.db/scratch \
  -t /global/projectb/scratch/bjcole/at.sc.db/scratch \
  -sS --include-technical
