#!/bin/bash
#SBATCH --mail-user=bjcole@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -A gtrnd
#SBATCH -q genepool
#SBATCH -J download_SRA_set_016
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --output=download_SRA_set_016.out

#/global/projectb/scratch/bjcole/sratoolkit.2.9.6-1-ubuntu64/bin/prefetch.2.9.3 SRR8086586 -o /global/projectb/scratch/bjcole/at.sc.db/scratch/set_016 -t http
/global/projectb/scratch/bjcole/sratoolkit.2.9.6-1-ubuntu64/bin/fasterq-dump SRR8086586 \
  -o set_016.fastq \
  -O /global/projectb/scratch/bjcole/at.sc.db/scratch \
  -t /global/projectb/scratch/bjcole/at.sc.db/scratch \
  -sS --include-technical
