sbatch src/filter/filter_ss_001.bs &
sbatch src/filter/filter_ss_002.bs &
sbatch src/filter/filter_ss_003.bs &
sbatch src/filter/filter_sc_004.bs &
sbatch src/filter/filter_sc_005.bs &
sbatch src/filter/filter_sc_006.bs &
sbatch src/filter/filter_sc_007.bs &
sbatch src/filter/filter_sc_008.bs &
sbatch src/filter/filter_sc_009.bs &
sbatch src/filter/filter_sc_010.bs &
sbatch src/filter/filter_zc_011.bs &
sbatch src/filter/filter_rc_012.bs &
sbatch src/filter/filter_rc_013.bs &
sbatch src/filter/filter_rc_014.bs &
sbatch src/filter/filter_rc_015.bs &
sbatch src/filter/filter_jsh_016.bs &
sbatch src/filter/filter_js_017.bs &
sbatch src/filter/filter_js_018.bs &
sbatch src/filter/filter_dc_019.bs &
sbatch src/filter/filter_dc_020.bs &
sbatch src/filter/filter_dc_021.bs &
sbatch src/filter/filter_dc_022.bs &
