sbatch src/download_set_001.bs &
sbatch src/download_set_002.bs &
sbatch src/download_set_003.bs &
sbatch src/download_set_004.bs &
sbatch src/download_set_005.bs &
sbatch src/download_set_006.bs &
sbatch src/download_set_007.bs &
sbatch src/download_set_008.bs &
sbatch src/download_set_009.bs &
sbatch src/download_set_010.bs &
sbatch src/download_set_011.bs &
sbatch src/download_set_012.bs &
sbatch src/download_set_013.bs &
sbatch src/download_set_014.bs &
sbatch src/download_set_015.bs &
sbatch src/download_set_016.bs &
sbatch src/download_set_017.bs &
sbatch src/download_set_018.bs &
sbatch src/download_set_019.bs &
sbatch src/download_set_020.bs &
sbatch src/download_set_021.bs &
sbatch src/download_set_022.bs &
